[versions]
firebaseBom = "34.8.0"
jaudiotagger = "2.0.3"
kotlinxCollectionsImmutable = "0.4.0"
ksp = "2.3.4"
materialColorUtilitiesAndroid = "4.1.0"
kotlin = "2.3.0"
androidx-palette = "1.0.0"
androidxCore = "1.17.0"
androidxCoreSplashscreen = "1.2.0"
androidxActivity = "1.12.2"
androidGradlePlugin = "9.1.0-alpha05"
kotlinxCoroutines = "1.10.2"
coil3Compose = "3.3.0"
androidxRoom = "2.8.4"
androidxDatastore = "1.2.0"
okio = "3.16.4"
androidxMedia3 = "1.9.0"
androidxTestRunner = "1.7.0"
googleService = "4.4.4"
firebaseCrashlytics = "3.0.6"
reorderable = "3.0.0"
kotlinxSerializationJson = "1.9.0"
ktor = "3.3.3"
koin-bom = "4.1.1"
napierVersion = "2.7.1"
sqlite = "2.6.2"
coreKtx = "1.7.0"
junit = "4.13.2"
junitVersion = "1.3.0"
vlcj = "4.11.0"
paparazzi = "1.3.5"
workRuntimeKtx = "2.11.0"
ktlint = "12.2.0"
spotless = "8.1.0"
pagingCommonVersion = "3.4.0-rc01"
lifecycle = "2.10.0"
materialIconsExtended = "1.7.3"
baselineprofile = "1.4.1"
benchmarkMacroJunit4 = "1.4.1"
uiautomator = "2.4.0-alpha07"
testRules = "1.7.0"
jetbrains-compose = "1.11.0-alpha01"
androidx-compose = "1.11.0-alpha03"
turbine = "1.2.1"
retainedmodel = "1.0.2"
nav3Ui = "1.1.0-alpha01"
nav3Runtime = "1.0.0"
navigationevent = "1.0.0"
expresso = "3.7.0"
popuphost = "1.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "androidx-palette" }
androidx-sqlite-api = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3Compose" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
jaudiotagger = { module = "org:jaudiotagger", version.ref = "jaudiotagger" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "kotlinxCoroutines" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
coil3-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil3Compose" }
coil3-video = { group = "io.coil-kt.coil3", name = "coil-video", version.ref = "coil3Compose" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
material-color-utilities-android = { module = "com.materialkolor:material-color-utilities-android", version.ref = "materialColorUtilitiesAndroid" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidxRoom" }
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDatastore" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastore" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "androidxMedia3" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidxMedia3" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "androidxMedia3" }
androidx-media3-ui-compose = { group = "androidx.media3", name = "media3-ui-compose", version.ref = "androidxMedia3" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
napier = { group = "io.github.aakira", name = "napier", version.ref = "napierVersion" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "expresso" }
paparazzi = { group = "app.cash.paparazzi", name = "paparazzi", version.ref = "paparazzi" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
vlcj = { module = "uk.co.caprica:vlcj", version.ref = "vlcj" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtx" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "pagingCommonVersion" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCommonVersion" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidxRoom" }
navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Runtime" }
navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "nav3Ui" }
navigationevent-compose = { module = "org.jetbrains.androidx.navigationevent:navigationevent-compose", version.ref = "navigationevent" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
compose-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidx-compose" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidx-compose" }
jetbrains-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetbrains-compose" }
jetbrains-compose-ui-util = { module = "org.jetbrains.compose.ui:ui-util", version.ref = "jetbrains-compose" }
jetbrains-compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "jetbrains-compose" }
jetbrains-compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "jetbrains-compose" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }
jetbrains-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "jetbrains-compose" }
jetbrains-compose-animation = { module = "org.jetbrains.compose.animation:animation", version.ref = "jetbrains-compose" }
jetbrains-compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "jetbrains-compose" }
jetbrains-compose-ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "jetbrains-compose" }
jetbrains-compose-desktop = { module = "org.jetbrains.compose.desktop:desktop", version.ref = "jetbrains-compose" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
retainedmodel = { group = "io.github.andannn", name = "retainedmodel", version.ref = "retainedmodel" }
popuphost = { group = "io.github.andannn", name = "popuphost", version.ref = "popuphost" }

# dependecy in build-logic
composeCompiler-gradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
ktlint-gradlePlugin = { group = "org.jlleitschuh.gradle", name = "ktlint-gradle", version.ref = "ktlint" }
android-kmp-library-gradlePlugin = { group = "com.android.kotlin.multiplatform.library", name = "com.android.kotlin.multiplatform.library.gradle.plugin", version.ref = "androidGradlePlugin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
google-service = { id = "com.google.gms.google-services", version.ref = "googleService" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "androidxRoom" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
